<h2>Amostragens</h2>

In [2]:
import numpy as np
import pandas as pd

In [3]:
enem_sp = pd.read_csv('~/Documents/curso_estatística/enem_2019_tratado.csv', sep=',', encoding='iso-8859-1')

In [4]:
enem_sp.head()

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
0,"1,90E+11",Santa Isabel,22,M,1,parda,1,1,não_respondeu,NaN,...,600.2,Inglês,1.0,160.0,200.0,180.0,200.0,200.0,940.0,Sim
1,"1,90E+11",São Paulo,17,F,1,parda,1,2,privada,15567761.0,...,731.8,Inglês,1.0,160.0,120.0,200.0,200.0,200.0,880.0,Não
2,"1,90E+11",São Bernardo do Campo,19,M,1,parda,1,2,pública,35904958.0,...,393.2,Espanhol,1.0,80.0,160.0,120.0,100.0,100.0,560.0,Sim
3,"1,90E+11",Embu-Guaçu,17,F,1,parda,1,2,pública,NaN,...,419.2,Inglês,1.0,120.0,120.0,120.0,120.0,80.0,560.0,Sim
4,"1,90E+11",Guarulhos,23,F,1,branca,1,1,não_respondeu,NaN,...,796.1,Inglês,1.0,160.0,200.0,180.0,180.0,160.0,880.0,Sim

In [5]:
enem_campinas = enem_sp.loc[enem_sp.NO_MUNICIPIO_RESIDENCIA == 'Campinas']

In [9]:
enem_campinas.head(10)

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
15,"1,90E+11",Campinas,17,F,1,branca,1,1,não_respondeu,NaN,...,496.5,Inglês,1.0,160.0,120.0,140.0,140.0,120.0,680.0,Sim
31,"1,90E+11",Campinas,19,F,1,parda,1,1,não_respondeu,NaN,...,73.1,Inglês,1.0,140.0,120.0,160.0,140.0,160.0,720.0,Sim
51,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,NaN,...,417.5,Inglês,1.0,160.0,140.0,160.0,120.0,160.0,740.0,Sim
116,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,26078562.0,...,480.5,Espanhol,1.0,120.0,60.0,60.0,100.0,0.0,340.0,Sim
169,"1,90E+11",Campinas,17,M,1,branca,1,2,privada,NaN,...,624.4,Inglês,1.0,140.0,120.0,140.0,160.0,160.0,720.0,Sim
186,"1,90E+11",Campinas,19,F,1,branca,1,1,não_respondeu,NaN,...,628.5,Inglês,1.0,120.0,120.0,120.0,120.0,80.0,560.0,Sim
236,"1,90E+11",Campinas,17,F,1,preta,1,2,privada,35112859.0,...,499.8,Inglês,1.0,160.0,120.0,120.0,160.0,200.0,760.0,Sim
325,"1,90E+11",Campinas,17,M,1,parda,1,2,pública,35907376.0,...,509.3,Inglês,1.0,80.0,120.0,100.0,100.0,80.0,480.0,Sim
401,"1,90E+11",Campinas,18,F,1,branca,1,1,não_respondeu,NaN,...,68.6,Inglês,1.0,160.0,160.0,180.0,160.0,200.0,860.0,Sim
469,"1,90E+11",Campinas,18,M,1,nao_declarado,1,1,não_respondeu,NaN,...,669.4,Inglês,1.0,140.0,180.0,120.0,160.0,120.0,720.0,Sim

In [10]:
enem_campinas.shape

(13198, 28)

<h2>Amostragem Aleatória Simples</h2>
<h4>Seleção executada por meio de sorteio, sem nenhum filtro.</h4>

In [29]:
# Semente, toda vez que roda gera o mesmo resultado
np.random.seed(1)

In [30]:
# Pega uma amostragem aleatória, 20%
amos_simples = enem_campinas.sample(frac=0.20)

In [38]:
amos_simples

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
327999,"1,90E+11",Campinas,20,M,1,preta,1,1,não_respondeu,NaN,...,459.6,Inglês,1.0,180.0,200.0,180.0,200.0,200.0,960.0,Sim
235222,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,35018296.0,...,48.8,Inglês,1.0,160.0,180.0,160.0,140.0,140.0,780.0,Sim
134221,"1,90E+11",Campinas,18,F,1,parda,1,2,pública,NaN,...,429.9,Inglês,1.0,100.0,120.0,100.0,80.0,100.0,500.0,Sim
358407,"1,90E+11",Campinas,25,M,0,parda,1,1,não_respondeu,NaN,...,687.4,Espanhol,1.0,140.0,120.0,120.0,140.0,140.0,660.0,Não
173364,"1,90E+11",Campinas,18,M,1,parda,1,1,não_respondeu,NaN,...,617.9,Inglês,1.0,140.0,120.0,140.0,140.0,80.0,620.0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452747,"1,90E+11",Campinas,45,F,1,branca,1,1,não_respondeu,NaN,...,373.5,Espanhol,1.0,80.0,80.0,80.0,80.0,80.0,400.0,Sim
362918,"1,90E+11",Campinas,19,M,1,preta,1,1,não_respondeu,NaN,...,450.7,Inglês,1.0,120.0,40.0,40.0,120.0,0.0,320.0,Sim
221397,"1,90E+11",Campinas,19,F,1,branca,1,1,não_respondeu,NaN,...,524.8,Espanhol,1.0,120.0,120.0,120.0,120.0,100.0,580.0,Sim
76628,"1,90E+11",Campinas,17,M,0,branca,1,2,pública,35018797.0,...,649.7,Inglês,1.0,120.0,120.0,120.0,120.0,80.0,560.0,Sim
126402,"1,90E+11",Campinas,17,F,1,parda,1,2,pública,35039901.0,...,376.6,Espanhol,1.0,120.0,160.0,140.0,120.0,140.0,680.0,Sim

In [12]:
# Seleciona aleatóriamente 3000 registros
amos_simples = enem_campinas.sample(3000)

In [13]:
amos_simples

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
57191,"1,90E+11",Campinas,17,F,1,amarela,1,2,pública,35045937.0,...,653.8,Inglês,1.0,120.0,120.0,120.0,140.0,120.0,620.0,Sim
215078,"1,90E+11",Campinas,17,F,1,parda,1,2,pública,35018880.0,...,507.8,Inglês,1.0,120.0,120.0,120.0,120.0,100.0,580.0,Sim
430770,"1,90E+11",Campinas,18,M,1,branca,1,2,privada,35112902.0,...,823.3,Inglês,1.0,140.0,180.0,120.0,160.0,160.0,760.0,Sim
409180,"1,90E+11",Campinas,19,F,1,preta,1,2,pública,35047120.0,...,574.7,Inglês,1.0,120.0,120.0,120.0,120.0,140.0,620.0,Sim
429862,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,35812900.0,...,522.7,Inglês,1.0,140.0,120.0,120.0,160.0,100.0,640.0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238949,"1,90E+11",Campinas,22,F,1,preta,1,1,não_respondeu,NaN,...,601.2,Inglês,1.0,160.0,120.0,160.0,160.0,180.0,780.0,Sim
242711,"1,90E+11",Campinas,17,F,1,parda,1,2,privada,35467765.0,...,628.3,Inglês,1.0,160.0,140.0,160.0,160.0,180.0,800.0,Sim
467039,"1,90E+11",Campinas,17,F,1,preta,1,2,pública,NaN,...,382.6,Inglês,1.0,80.0,120.0,100.0,100.0,100.0,500.0,Sim
189967,"1,90E+11",Campinas,19,F,1,parda,1,1,não_respondeu,NaN,...,455.1,Espanhol,1.0,100.0,140.0,120.0,140.0,120.0,620.0,Não
282921,"1,90E+11",Campinas,18,F,1,parda,1,2,pública,35812900.0,...,511.2,Inglês,1.0,120.0,140.0,120.0,140.0,140.0,660.0,Sim

Outra maneira

In [46]:
np.random.seed(2)

In [47]:
# Faz uma escolha do tamanho total, numeros em 0 e 1. Usa 80% vai ser numero 0 e 20% numero 1
amostra = np.random.choice(a=[0,1], size=13198, replace=True, p=[0.8, 0.2])

In [48]:
amostra

array([0, 0, 0, ..., 0, 0, 1])

In [49]:
len(amostra[amostra==0])

10566

In [50]:
len(amostra[amostra==1])

2632

In [51]:
amos_simples = enem_campinas.loc[amostra == 1]

In [52]:
amos_simples

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
949,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,35924573.0,...,601.4,Inglês,1.0,160.0,120.0,120.0,140.0,120.0,660.0,Sim
1058,"1,90E+11",Campinas,19,M,1,parda,1,1,não_respondeu,NaN,...,474.6,Inglês,1.0,120.0,120.0,120.0,160.0,100.0,620.0,Sim
1980,"1,90E+11",Campinas,17,F,1,parda,1,2,pública,35018302.0,...,479.9,Inglês,1.0,120.0,120.0,120.0,140.0,120.0,620.0,Não
2053,"1,90E+11",Campinas,18,F,1,parda,1,1,não_respondeu,NaN,...,424.2,Inglês,1.0,100.0,40.0,20.0,80.0,0.0,240.0,Sim
2328,"1,90E+11",Campinas,20,F,1,parda,2,1,não_respondeu,NaN,...,552.5,Espanhol,1.0,120.0,120.0,100.0,100.0,80.0,520.0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498946,"1,90E+11",Campinas,17,M,1,parda,1,2,pública,35018797.0,...,484.1,Inglês,1.0,120.0,120.0,120.0,120.0,80.0,560.0,Sim
499198,"1,90E+11",Campinas,18,M,1,preta,1,2,pública,35018363.0,...,666.4,Inglês,1.0,120.0,120.0,120.0,100.0,80.0,540.0,Sim
499258,"1,90E+11",Campinas,21,F,1,preta,1,1,não_respondeu,NaN,...,503.6,Inglês,1.0,120.0,120.0,120.0,140.0,120.0,620.0,Sim
499691,"1,90E+11",Campinas,17,F,1,preta,1,2,pública,35018089.0,...,770.3,Inglês,1.0,120.0,120.0,120.0,160.0,80.0,600.0,Sim
499883,"1,90E+11",Campinas,20,F,1,branca,1,1,não_respondeu,NaN,...,701.1,Inglês,1.0,160.0,200.0,200.0,200.0,180.0,940.0,Sim

<h2>Amostragem Sistemática</h2>
<h4>Membros da população são ordenados numericamente e são selecionados aleatoriamente, obedecendo uma sequência numérica. (Ex.: criação de números para cada amostra e seleção obedecendo uma ordem numérica.)</h4>

In [11]:
enem_campinas.shape

(13198, 28)

In [12]:
np.random.seed(2)
inicio = np.random.choice(10, 1)

In [17]:
inicio

array([8])

In [19]:
amostra2 = np.arange(inicio, 13198, 100)
amostra2

/tmp/ipykernel_4971/205869997.py:1: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  amostra2 = np.arange(inicio, 13198, 100)

array([    8,   108,   208,   308,   408,   508,   608,   708,   808,
         908,  1008,  1108,  1208,  1308,  1408,  1508,  1608,  1708,
        1808,  1908,  2008,  2108,  2208,  2308,  2408,  2508,  2608,
        2708,  2808,  2908,  3008,  3108,  3208,  3308,  3408,  3508,
        3608,  3708,  3808,  3908,  4008,  4108,  4208,  4308,  4408,
        4508,  4608,  4708,  4808,  4908,  5008,  5108,  5208,  5308,
        5408,  5508,  5608,  5708,  5808,  5908,  6008,  6108,  6208,
        6308,  6408,  6508,  6608,  6708,  6808,  6908,  7008,  7108,
        7208,  7308,  7408,  7508,  7608,  7708,  7808,  7908,  8008,
        8108,  8208,  8308,  8408,  8508,  8608,  8708,  8808,  8908,
        9008,  9108,  9208,  9308,  9408,  9508,  9608,  9708,  9808,
        9908, 10008, 10108, 10208, 10308, 10408, 10508, 10608, 10708,
       10808, 10908, 11008, 11108, 11208, 11308, 11408, 11508, 11608,
       11708, 11808, 11908, 12008, 12108, 12208, 12308, 12408, 12508,
       12608, 12708, 12808, 12908, 13008, 13108])

In [20]:
# iloc busca os índices
amos_sistematica = enem_campinas.iloc[amostra2,:]

In [21]:
amos_sistematica

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
401,"1,90E+11",Campinas,18,F,1,branca,1,1,não_respondeu,NaN,...,68.6,Inglês,1.0,160.0,160.0,180.0,160.0,200.0,860.0,Sim
5079,"1,90E+11",Campinas,18,F,1,branca,1,2,pública,35018855.0,...,419.9,Inglês,1.0,140.0,120.0,120.0,120.0,140.0,640.0,Sim
9218,"1,90E+11",Campinas,19,F,1,branca,1,1,não_respondeu,NaN,...,617.1,Inglês,1.0,120.0,120.0,120.0,120.0,120.0,600.0,Sim
13685,"1,90E+11",Campinas,20,M,1,parda,1,1,não_respondeu,NaN,...,576.4,Inglês,1.0,160.0,200.0,180.0,200.0,180.0,920.0,Sim
18239,"1,90E+11",Campinas,20,M,1,branca,1,1,não_respondeu,NaN,...,796.2,Inglês,1.0,160.0,200.0,200.0,200.0,200.0,960.0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
481894,"1,90E+11",Campinas,34,M,1,parda,1,1,não_respondeu,NaN,...,932.1,Inglês,1.0,140.0,120.0,160.0,160.0,160.0,740.0,Sim
485805,"1,90E+11",Campinas,16,F,1,branca,1,2,pública,35039901.0,...,441.6,Inglês,1.0,120.0,120.0,100.0,120.0,0.0,460.0,Sim
488958,"1,90E+11",Campinas,19,F,1,branca,1,1,não_respondeu,NaN,...,492.9,Inglês,1.0,160.0,120.0,140.0,120.0,140.0,680.0,Sim
492626,"1,90E+11",Campinas,21,M,1,branca,1,1,não_respondeu,NaN,...,51.1,Inglês,1.0,120.0,120.0,120.0,100.0,0.0,460.0,Sim
496410,"1,90E+11",Campinas,19,M,1,preta,1,1,não_respondeu,NaN,...,404.4,Inglês,1.0,100.0,80.0,80.0,80.0,40.0,380.0,Sim

In [26]:
np.random.seed(30)

In [27]:
inicio = np.random.choice(10,1)
passo = np.random.randint(100, 150, 1)

In [28]:
inicio

array([5])

In [29]:
passo

array([137])

In [30]:
amostra2 = np.arange(inicio, 13198, passo)
amostra2

/tmp/ipykernel_4971/1894288214.py:1: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  amostra2 = np.arange(inicio, 13198, passo)

array([    5,   142,   279,   416,   553,   690,   827,   964,  1101,
        1238,  1375,  1512,  1649,  1786,  1923,  2060,  2197,  2334,
        2471,  2608,  2745,  2882,  3019,  3156,  3293,  3430,  3567,
        3704,  3841,  3978,  4115,  4252,  4389,  4526,  4663,  4800,
        4937,  5074,  5211,  5348,  5485,  5622,  5759,  5896,  6033,
        6170,  6307,  6444,  6581,  6718,  6855,  6992,  7129,  7266,
        7403,  7540,  7677,  7814,  7951,  8088,  8225,  8362,  8499,
        8636,  8773,  8910,  9047,  9184,  9321,  9458,  9595,  9732,
        9869, 10006, 10143, 10280, 10417, 10554, 10691, 10828, 10965,
       11102, 11239, 11376, 11513, 11650, 11787, 11924, 12061, 12198,
       12335, 12472, 12609, 12746, 12883, 13020, 13157])

In [31]:
amostra2_camp = enem_campinas.iloc[amostra2,:]

In [32]:
amostra2_camp

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
186,"1,90E+11",Campinas,19,F,1,branca,1,1,não_respondeu,NaN,...,628.5,Inglês,1.0,120.0,120.0,120.0,120.0,80.0,560.0,Sim
6519,"1,90E+11",Campinas,26,M,0,preta,1,1,não_respondeu,NaN,...,364.9,Inglês,1.0,120.0,200.0,140.0,120.0,200.0,780.0,Não
12280,"1,90E+11",Campinas,20,F,1,branca,1,1,não_respondeu,NaN,...,46.7,Inglês,1.0,120.0,120.0,80.0,100.0,20.0,440.0,Sim
18436,"1,90E+11",Campinas,22,F,2,preta,1,1,não_respondeu,NaN,...,586.7,Espanhol,1.0,100.0,120.0,120.0,100.0,80.0,520.0,Sim
23717,"1,90E+11",Campinas,18,M,1,parda,1,1,não_respondeu,NaN,...,48.4,Inglês,1.0,80.0,80.0,80.0,80.0,0.0,320.0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
478519,"1,90E+11",Campinas,23,F,1,branca,1,1,não_respondeu,NaN,...,592.2,Inglês,1.0,140.0,120.0,120.0,120.0,180.0,680.0,Sim
483431,"1,90E+11",Campinas,18,F,1,branca,1,1,não_respondeu,NaN,...,55.2,Inglês,1.0,140.0,120.0,120.0,140.0,100.0,620.0,Sim
488340,"1,90E+11",Campinas,19,F,1,branca,1,1,não_respondeu,NaN,...,542.3,Espanhol,1.0,120.0,120.0,140.0,120.0,80.0,580.0,Sim
493180,"1,90E+11",Campinas,33,F,0,branca,1,1,não_respondeu,NaN,...,396.7,Inglês,1.0,80.0,40.0,40.0,80.0,0.0,240.0,Sim
498126,"1,90E+11",Campinas,17,M,1,branca,1,2,privada,NaN,...,653.7,Inglês,1.0,120.0,120.0,120.0,100.0,80.0,540.0,Sim

<h2>Amostragem Estratificada</h2>
<h4>Divisão da população em grupos e seleção aleatória de uma amosra de cada grupo.</h4>

In [6]:
enem_campinas['RACA'].value_counts()

RACA
branca           7507
parda            3652
preta            1510
amarela           279
nao_declarado     205
indígena           45
Name: count, dtype: int64

<h4>Para quantidade pequena de grupos</h4>

In [16]:
branca = enem_campinas.loc[enem_campinas.RACA == 'branca'].sample(frac=0.15)
branca.shape

(1126, 28)

In [17]:
parda = enem_campinas.loc[enem_campinas.RACA == 'parda'].sample(frac=0.15)
parda.shape

(548, 28)

In [18]:
preta = enem_campinas.loc[enem_campinas.RACA == 'preta'].sample(frac=0.15)
preta.shape

(226, 28)

In [19]:
amarela = enem_campinas.loc[enem_campinas.RACA == 'amarela'].sample(frac=0.15)
amarela.shape

(42, 28)

In [20]:
nd = enem_campinas.loc[enem_campinas.RACA == 'nao_declarado'].sample(frac=0.15)
nd.shape

(31, 28)

In [21]:
indigena = enem_campinas.loc[enem_campinas.RACA == 'indígena'].sample(frac=0.15)
indigena.shape

(7, 28)

In [22]:
amos_estra = pd.concat([branca, parda, preta, amarela, nd, indigena])

In [23]:
amos_estra

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
261142,"1,90E+11",Campinas,18,F,1,branca,1,1,não_respondeu,NaN,...,663.3,Inglês,1.0,160.0,120.0,160.0,140.0,120.0,700.0,Sim
435913,"1,90E+11",Campinas,25,M,1,branca,1,1,não_respondeu,NaN,...,480.1,Inglês,1.0,140.0,120.0,100.0,80.0,80.0,520.0,Não
413056,"1,90E+11",Campinas,18,F,1,branca,1,1,não_respondeu,NaN,...,604.3,Inglês,1.0,120.0,120.0,140.0,120.0,100.0,600.0,Sim
252864,"1,90E+11",Campinas,18,F,1,branca,1,1,não_respondeu,NaN,...,526.5,Inglês,1.0,120.0,120.0,120.0,120.0,0.0,480.0,Sim
20092,"1,90E+11",Campinas,19,F,1,branca,1,1,não_respondeu,NaN,...,435.1,Espanhol,1.0,100.0,120.0,100.0,120.0,100.0,540.0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109333,"1,90E+11",Campinas,18,M,1,indígena,1,2,privada,35112859.0,...,378.4,Inglês,1.0,140.0,160.0,160.0,160.0,160.0,780.0,Sim
210698,"1,90E+11",Campinas,18,M,1,indígena,1,2,pública,35047200.0,...,638.9,Inglês,1.0,120.0,120.0,120.0,120.0,80.0,560.0,Sim
66153,"1,90E+11",Campinas,20,F,1,indígena,1,1,não_respondeu,NaN,...,689.8,Espanhol,1.0,140.0,140.0,160.0,180.0,180.0,800.0,Sim
52128,"1,90E+11",Campinas,19,F,1,indígena,1,1,não_respondeu,NaN,...,414.4,Espanhol,1.0,120.0,120.0,120.0,120.0,40.0,520.0,Sim
349878,"1,90E+11",Campinas,17,F,1,indígena,3,2,pública,35045718.0,...,434.9,Inglês,1.0,120.0,120.0,100.0,120.0,160.0,620.0,Sim

<h4>Grandes quantidades de grupos</h4>

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
X_treino, X_teste, y_treino, amos_estra = train_test_split(
    # extratificando da tabela de dados do enem_campinas um tamanho de teste e 20%, dropando uma parte para ficar com apenas uma das partes
    # axis=1 -> coluna, axis=0 -> linha
    enem_campinas.drop('RACA', axis=1), 
    enem_campinas['RACA'], 
    stratify=enem_campinas['RACA'], 
    test_size=0.20
)

In [27]:
amos_estra.shape

(2640,)

In [28]:
amos_estra.value_counts()

RACA
branca           1502
parda             730
preta             302
amarela            56
nao_declarado      41
indígena            9
Name: count, dtype: int64

In [29]:
amos_estra = amos_estra.index

In [30]:
amos_estra

Index([356492, 209446, 204127,  27993, 171454, 372538, 475492, 263755, 412700,
       482827,
       ...
       460156, 241418, 376724, 306815, 259041,  26616, 474166,  31330, 188578,
       352285],
      dtype='int64', length=2640)

In [31]:
amos_estra_camp = enem_campinas.loc[amos_estra,:]

In [32]:
amos_estra_camp

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
356492,"1,90E+11",Campinas,19,F,1,preta,1,2,pública,NaN,...,64.6,Inglês,1.0,140.0,120.0,120.0,120.0,80.0,580.0,Sim
209446,"1,90E+11",Campinas,19,M,1,branca,1,2,pública,35042626.0,...,385.6,Espanhol,1.0,100.0,120.0,100.0,120.0,0.0,440.0,Sim
204127,"1,90E+11",Campinas,17,F,1,nao_declarado,1,2,pública,35018260.0,...,485.6,Inglês,1.0,120.0,40.0,40.0,120.0,20.0,340.0,Sim
27993,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,NaN,...,493.3,Inglês,1.0,120.0,120.0,120.0,120.0,100.0,580.0,Sim
171454,"1,90E+11",Campinas,43,M,0,parda,1,1,não_respondeu,NaN,...,572.5,Espanhol,1.0,100.0,120.0,120.0,100.0,100.0,540.0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26616,"1,90E+11",Campinas,17,F,1,branca,1,2,privada,35172510.0,...,478.7,Inglês,1.0,160.0,200.0,160.0,160.0,160.0,840.0,Sim
474166,"1,90E+11",Campinas,20,F,1,branca,1,1,não_respondeu,NaN,...,516.4,Inglês,1.0,160.0,120.0,180.0,180.0,200.0,840.0,Sim
31330,"1,90E+11",Campinas,17,F,1,preta,1,2,pública,NaN,...,446.1,Espanhol,1.0,120.0,120.0,120.0,120.0,160.0,640.0,Sim
188578,"1,90E+11",Campinas,18,F,1,branca,1,2,pública,35436012.0,...,459.6,Espanhol,1.0,140.0,180.0,160.0,140.0,140.0,760.0,Sim
352285,"1,90E+11",Campinas,18,F,1,parda,1,1,não_respondeu,NaN,...,545.7,Espanhol,1.0,80.0,40.0,40.0,120.0,0.0,280.0,Sim

<h2>Conglomerado (Agrupamento)</h2>
<h4>Divisão da população em grupos com características similares, porém heterogêneas, e seleção aleatória de alguns grupos para analisar todos os elementos destes grupos. (Ex.: Divisão da população de escolas estaduais por região, enfermeiros de uma rede de hospitais)</h4>

In [6]:
escolas_publicas = enem_campinas.loc[enem_campinas.ESCOLA == 'pública']

In [7]:
escolas_publicas.shape

(4175, 28)

In [8]:
escolas_publicas

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
51,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,NaN,...,417.5,Inglês,1.0,160.0,140.0,160.0,120.0,160.0,740.0,Sim
116,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,26078562.0,...,480.5,Espanhol,1.0,120.0,60.0,60.0,100.0,0.0,340.0,Sim
325,"1,90E+11",Campinas,17,M,1,parda,1,2,pública,35907376.0,...,509.3,Inglês,1.0,80.0,120.0,100.0,100.0,80.0,480.0,Sim
949,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,35924573.0,...,601.4,Inglês,1.0,160.0,120.0,120.0,140.0,120.0,660.0,Sim
1004,"1,90E+11",Campinas,24,F,1,branca,1,2,pública,35980158.0,...,359.8,Espanhol,1.0,120.0,40.0,100.0,100.0,60.0,420.0,Não
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499530,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,35042651.0,...,491.6,Inglês,1.0,140.0,120.0,120.0,160.0,120.0,660.0,Sim
499640,"1,90E+11",Campinas,22,M,1,preta,1,2,pública,35018533.0,...,365.4,Espanhol,1.0,80.0,60.0,60.0,80.0,0.0,280.0,Sim
499691,"1,90E+11",Campinas,17,F,1,preta,1,2,pública,35018089.0,...,770.3,Inglês,1.0,120.0,120.0,120.0,160.0,80.0,600.0,Sim
499749,"1,90E+11",Campinas,17,M,1,branca,1,2,pública,35040400.0,...,405.1,Espanhol,1.0,120.0,80.0,80.0,100.0,60.0,440.0,Sim
499862,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,35018879.0,...,40.3,Inglês,1.0,120.0,120.0,120.0,120.0,160.0,640.0,Sim

In [9]:
amostras = escolas_publicas['CO_ESCOLA'].value_counts()
amostras

CO_ESCOLA
35045937.0    152
35018363.0    134
35018797.0    124
35018879.0    110
35018326.0    109
             ...
35462822.0      1
35058836.0      1
35112926.0      1
35017255.0      1
35047053.0      1
Name: count, Length: 186, dtype: int64

In [10]:
amostras.index

Index([35045937.0, 35018363.0, 35018797.0, 35018879.0, 35018326.0, 35047200.0,
       35901097.0, 35045949.0, 35018235.0, 35018302.0,
       ...
       35018181.0, 35445757.0, 35045724.0, 35432842.0, 35039834.0, 35462822.0,
       35058836.0, 35112926.0, 35017255.0, 35047053.0],
      dtype='float64', name='CO_ESCOLA', length=186)

In [33]:
amostragem = np.random.choice(a=[0,1], size=186, replace=True, p=[0.85, 0.15])
amostragem

array([0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [34]:
amos_conglomerado = amostras.loc[amostragem == 1]

In [35]:
amos_conglomerado

CO_ESCOLA
35018797.0    124
35018879.0    110
35018326.0    109
35045718.0     67
35112859.0     39
35018806.0     35
35924544.0     30
35980158.0     27
35045676.0     23
35018247.0     19
35018910.0     13
35037965.0     13
35901131.0     13
35127784.0      9
35112562.0      8
35924933.0      8
35047156.0      7
35045585.0      6
35131982.0      6
35466682.0      5
35579403.0      3
35907388.0      3
35045524.0      2
26127741.0      1
35049451.0      1
26078562.0      1
23128178.0      1
35150095.0      1
35462822.0      1
Name: count, dtype: int64

In [36]:
amos_conglomerado.shape

(29,)

In [37]:
amos_conglomerado.index

Index([35018797.0, 35018879.0, 35018326.0, 35045718.0, 35112859.0, 35018806.0,
       35924544.0, 35980158.0, 35045676.0, 35018247.0, 35018910.0, 35037965.0,
       35901131.0, 35127784.0, 35112562.0, 35924933.0, 35047156.0, 35045585.0,
       35131982.0, 35466682.0, 35579403.0, 35907388.0, 35045524.0, 26127741.0,
       35049451.0, 26078562.0, 23128178.0, 35150095.0, 35462822.0],
      dtype='float64', name='CO_ESCOLA')

In [38]:
amos_conglomerado = escolas_publicas.loc[escolas_publicas['CO_ESCOLA'].isin([
    35018797.0, 35018879.0, 35018326.0, 35045718.0, 35112859.0, 35018806.0,
    35924544.0, 35980158.0, 35045676.0, 35018247.0, 35018910.0, 35037965.0,
    35901131.0, 35127784.0, 35112562.0, 35924933.0, 35047156.0, 35045585.0,
    35131982.0, 35466682.0, 35579403.0, 35907388.0, 35045524.0, 26127741.0,
    35049451.0, 26078562.0, 23128178.0, 35150095.0, 35462822.0])]

In [39]:
amos_conglomerado

,NU_INSCRICAO,NO_MUNICIPIO_RESIDENCIA,IDADE,SEXO,TP_ESTADO_CIVIL,RACA,TP_NACIONALIDADE,TP_ST_CONCLUSAO,ESCOLA,CO_ESCOLA,...,NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,COMP1,COMP2,COMP3,COMP4,COMP5,NOTA_REDACAO,INTERNET
116,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,26078562.0,...,480.5,Espanhol,1.0,120.0,60.0,60.0,100.0,0.0,340.0,Sim
1004,"1,90E+11",Campinas,24,F,1,branca,1,2,pública,35980158.0,...,359.8,Espanhol,1.0,120.0,40.0,100.0,100.0,60.0,420.0,Não
1177,"1,90E+11",Campinas,17,M,1,parda,1,2,pública,35924544.0,...,61.3,Inglês,1.0,120.0,120.0,140.0,120.0,180.0,680.0,Sim
1838,"1,90E+11",Campinas,18,F,1,branca,1,2,pública,35018326.0,...,656.6,Espanhol,1.0,100.0,120.0,120.0,100.0,120.0,560.0,Sim
2382,"1,90E+11",Campinas,28,F,2,parda,1,2,pública,35045718.0,...,611.6,Inglês,1.0,120.0,120.0,140.0,140.0,160.0,680.0,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
497800,"1,90E+11",Campinas,18,F,1,preta,1,2,pública,35018797.0,...,589.9,Inglês,1.0,100.0,120.0,100.0,100.0,80.0,500.0,Sim
498213,"1,90E+11",Campinas,17,M,1,branca,1,2,pública,35924544.0,...,454.3,Inglês,1.0,120.0,120.0,120.0,80.0,140.0,580.0,Sim
498693,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,35018326.0,...,460.2,Inglês,1.0,120.0,120.0,100.0,120.0,80.0,540.0,Sim
498946,"1,90E+11",Campinas,17,M,1,parda,1,2,pública,35018797.0,...,484.1,Inglês,1.0,120.0,120.0,120.0,120.0,80.0,560.0,Sim
499862,"1,90E+11",Campinas,17,F,1,branca,1,2,pública,35018879.0,...,40.3,Inglês,1.0,120.0,120.0,120.0,120.0,160.0,640.0,Sim